[package]
name = "lasttalon/monolith"
description = "A Luau collections library."
version = "0.1.1"
license = "MIT"
authors = ["LastTalon"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
